// frontend/src/components/ProductForm.vue
<script>
import { v4 as uuidv4 } from 'uuid';

export default {
  props: {
    defaultProduct: Object
  },
  data() {
    return {
      product:  JSON.parse(JSON.stringify(this.defaultProduct)),
    }
  },
  methods: {
      submitForm() {
          const p = {
              product_id: uuidv4(),
              product_name: this.product.productName,
              product_owner_name: this.product.productOwnerName,
              developers: this.product.developers.filter(developer => developer !== ''),
              scrum_master_name: this.product.scrumMasterName,
              start_date: this.product.startDate,
              methodology: this.product.methodology
          };
          this.$emit("new-product", JSON.stringify(p));
          this.product = JSON.parse(JSON.stringify(this.defaultProduct));
          console.log(this.defaultProduct);
      }
  }
}
</script>

<template>
  <div>
    <form @submit.prevent="submitForm">
      <label for="product_name">Product Name:</label>
      <input type="text" id="product_name" v-model="product.productName" required>

      <label for="product_owner_name">Product Owner Name:</label>
      <input type="text" id="product_owner_name" v-model="product.productOwnerName" required>

      <label for="developers">Developers:</label>
      <div v-for="(developer, index) in product.developers" :key="index">
        <input type="text" id="developers" v-model="product.developers[index]">
      </div>

      <label for="scrum_master_name">Scrum Master Name:</label>
      <input type="text" id="scrum_master_name" v-model="product.scrumMasterName" required>

      <label for="start_date">Start Date:</label>
      <label for="start_date">Start Date:</label>
      <input type="date" id="start_date" v-model="product.startDate" required>

      <label for="methodology">Methodology:</label>
      <select id="methodology" v-model="product.methodology">
        <option>Agile</option>
        <option>Waterfall</option>
      </select>

      <button type="submit">Add Product</button>
    </form>
  </div>
</template>

// frontend-react/src/components/ProductForm/ProductForm.jsx
import React from 'react';

function ProductForm() {
  const [productName, setProductName] = React.useState('');
  const [productOwnerName, setProductOwnerName] = React.useState('');
  const [scrumMasterName, setScrumMasterName] = React.useState('');
  const [startDate, setStartDate] = React.useState('');
  const [methodology, setMethodology] = React.useState('');

  function handleSubmit(e) {
    e.preventDefault();
    console.log('form submitted');
  }

  return (
    <>
	  <form onSubmit={handleSubmit}>
        <label htmlFor="product_name">Product Name:</label>
        <input type="text" id="product_name" value={productName} onChange={(e) => setProductName(e.target.value)} required />

        <label htmlFor="product_owner_name">Product Owner Name:</label>
        <input type="text" id="product_owner_name" value={productOwnerName} onChange={(e) => setProductOwnerName(e.target.value)} required />

{/*
        <label htmlFor="developers">Developers:</label>
        <div v-for="(developer, index) in product.developers" :key="index">
          <input type="text" id="developers" v-model="product.developers[index]" :required="index == 0">
        </div>
*/}

        <label htmlFor="scrum_master_name">Scrum Master Name:</label>
        <input type="text" id="scrum_master_name" value={scrumMasterName} onChange={(e) => setScrumMasterName(e.target.value)} required />

        <label htmlFor="start_date">Start Date:</label>
        <input type="date" id="start_date" value={startDate} onChange={(e) => setStartDate(e.target.value)} required />

        <label htmlFor="methodology">Methodology:</label>
        <select id="methodology" value={methodology} onChange={(e) => setMethodology(e.target.value)}>
          <option>Agile</option>
          <option>Waterfall</option>
        </select>

        <input type="submit" value="Add Product" />
      </form>
    </>
  ); 
}

export default ProductForm;
