// frontend/src/components/ProductList.vue
<script>
export default {
    data() {
        return {
	        fields: [
	          { key: 'product_name', label: 'Name'},
	          { key: 'product_owner_name', label: 'Owner'},
	          { key: 'developers', label: 'Developers'},
	          { key: 'scrum_master_name', label: 'Scrum Master'},
	          { key: 'start_date', label: 'Start Date'},
	          { key: 'methodology', label: 'Methodology'},
	          { key: 'product_id', label: 'ID'},
	          { key: 'edit', label: '' }
	        ]
      	}
    },
    props: {
        products: Array
    },
    methods: {
      clickEdit(product_id) {
	  	this.$emit("edit-product", product_id);
      }
  }
}
</script>

<template>
    <b-table striped :items="products" :fields="fields">
		<template #cell(edit)="row">
			<b-button v-b-modal.editProductModal size="sm" @click="clickEdit(row.item.product_id)">
			   Edit
			</b-button>
		</template>
		<template #cell(developers)="row">
			{{ row.item.developers.filter(developer => developer != null).join(', ') }}
		</template>
		<template #cell(product_id)="row">
			{{ row.item.product_id.substr(0, 10) }}..
		</template>
	</b-table>
</template>

// frontend-react/src/components/ProductList/ProductList.jsx
import React from 'react';
import useSWR from 'swr';

async function fetcher(endpoint) {
  const response = await fetch(endpoint);
  const json = await response.json();
  return json;
}

const ENDPOINT = 'https://fs.local/api/products';

function ProductList({showProductEditForm}) {
  // status: idle | loading | success | error
  const [status, setStatus] = React.useState('idle');
	const { data, isLoading, error } = useSWR(ENDPOINT, fetcher);
  
  return (
    <>
	    {isLoading && (
		    <p>Loading products…</p>
		  )}

	    {error && (
		    <p>Sorry, the products could not be retrieved.</p>
		  )}

			{data && (
	      <>
		      <p><strong>{data.length} products</strong></p>
		      <table>
		      	<thead>
		      		<tr>
			      		<th>Id</th>
			      		<th>Name</th>
			      		<th>Owner</th>
			      		<th>Developers</th>
			      		<th>Scrum Master</th>
			      		<th>Start Date</th>
			      		<th>Methodology</th>
			      		<th></th>
			      	</tr>
		      	</thead>
		      	<tbody>
		      		{data.map(product => 
		          	<tr key={product.product_id}>
		          		<td>{product.product_id}</td>
		          		<td>{product.product_name}</td>
		          		<td>{product.product_owner_name}</td>
		          		<td>{product.developers.filter(developer => developer != null).join(', ')}</td>
		          		<td>{product.scrum_master_name}</td>
		          		<td>{product.start_date}</td>
		          		<td>{product.methodology}</td>
		          		<td><button onClick={() => showProductEditForm(product.product_id)}>Edit</button></td>
		          	</tr>
		        	)}
		      	</tbody>
		      </table>
	      </>
      )}

    </>
  ); 
}

export default ProductList;
